on: push

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: npm

      - name: 🧰  Install
        run: npm ci --production-only

      - name: 📦  build
        run: npm run builds

  Perform tests:
    name: Test application
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 🧹 Run lint
        run: npm run lint

      - name: 🧪 test
        run: npm run test:prod -a
